#!/bin/bash
echo "apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: democratic
  namespace: kube-system
spec:
  chart: democratic-csi
  repo: https://democratic-csi.github.io/charts/
  targetNamespace: democratic-csi
  valuesContent: |-
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.nfs"

    # add note here about volume expansion requirements
    storageClasses:
    - name: truenas-ssd
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    volumeSnapshotClasses: 
    - name: truenas-ssd
    
    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: $nasAddress
          port: 80
          # use only 1 of apiKey or username/password
          # if both are present, apiKey is preferred
          # apiKey is only available starting in TrueNAS-12
          #apiKey:
          username: $nasUsername
          password: $nasPassword
          allowInsecure: true
          # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
          # leave unset for auto-detection
          apiVersion: 2
        sshConnection:
          host: $nasAddress
          port: 22
          username: $nasUsername
          # use either password or key
          password: $nasPassword
        zfs:
          datasetParentName: $nasPoolName/$clusterName/vols
          detachedSnapshotsDatasetParentName: $nasPoolName/$clusterName/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
          #datasetPermissionsAcls:
          #- "-m everyone@:full_set:allow"
          #- "-m u:kube:full_set:allow"

        nfs:
          #shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          shareHost: $nasAddress
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
"
