#!/bin/bash
echo "apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
spec:
  rules:
  - host: "$argo-fqdn"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 80
"
