#!/bin/bash
echo "apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-backup
  namespace: kube-system
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: nfs-provisioner
  valuesContent: |-
    nfs:
      server: "$nas_address"
      path: "$nfsPath"
    storageClass:
      name: "nfs-backup"
      reclaimPolicy: "Retain"
      provisionerName: "k8s-sigs.io/nfs-backup"  
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
"
